apiVersion: v1
kind: Service
metadata:
  name: dummysmfsvc
  namespace: testpod
  labels:
    type: smf
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 6000
    protocol: TCP
    targetPort: 6000
  selector:
    type: smf
