# SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: dummyamf
  namespace: testpod
  labels:
    type: amf
spec:
  containers:
  - image: docker.io/bhelankur/dummyamf:latest
    imagePullPolicy: Always
    name: dummyamf
    command: ["./dummyamf"]
