# SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: nrf
  labels:
    type: testpod
  namespace: testpod
spec:
  type: ClusterIP
  ports:
  - name: nrf
    targetPort: 29510
    port: 29510
  selector:
    type: testpod
