# SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: amf
  labels:
    type: testpod
  namespace: testpod
spec:
  type: ClusterIP
  ports:
  - name: amf
    targetPort: 29518
    port: 29518
  selector:
    type: testpod
